var mongoose = require('mongoose');

//Dlecaramos el schema de mongodb
var datSet = new mongoose.Schema({
    ID: {type: Number}, 
    Name: {type:String}, 
    Age: {type:Number}, 
    Photo: {type:String}, 
    Nationality: {type:String}, 
    Flag: {type:String}, 
    Overall: {type:Number}, 
    Potential: {type:Number}, 
    Club: {type:String}, 
    ClubLogo: {type:String}, 
    Value: {type:String}, 
    Wage: {type:String}, 
    Special: {type:Number}, 
    PreferredFoot: {type:String}, 
    InternationalReputation: {type:Number}, 
    WeakFoot: {type:Number}, 
    SkillMoves: {type:Number}, 
    WorkRate: {type:String}, 
    BodyType: {type:String}, 
    RealFace: {type:String}, 
    Position: {type:String}, 
    JerseyNumber: {type:String}, 
    Joined: {type:String}, 
    LoanedFrom: {type:Number}, 
    ContractValidUntil: {type:String}, 
    Height: {type:String}, 
    Weight: {type:String}, 
    Crossing: {type:Number}, 
    Finishing: {type:Number}, 
    HeadingAccuracy: {type:Number}, 
    ShortPassing: {type:Number}, 
    Volleys: {type:Number}, 
    Dribbling: {type:Number}, 
    Curve: {type:Number}, 
    FKAccuracy: {type:Number}, 
    LongPassing: {type:Number}, 
    BallControl: {type:Number}, 
    Acceleration: {type:Number}, 
    SprintSpeed: {type:Number}, 
    Agility: {type:Number}, 
    Reactions: {type:Number}, 
    Balance: {type:Number}, 
    ShotPower: {type:Number}, 
    Jumping: {type:Number}, 
    Stamina: {type:Number}, 
    Strength: {type:Number}, 
    LongShots: {type:Number}, 
    Aggression: {type:Number}, 
    Interceptions: {type:Number}, 
    Positioning: {type:Number}, 
    Vision: {type:Number}, 
    Penalties: {type:Number}, 
    Composure: {type:Number}, 
    Marking: {type:Number}, 
    StandingTackle: {type:Number}, 
    SlidingTackle: {type:Number}, 
    GKDiving: {type:Number}, 
    GKHandling: {type:Number}, 
    GKKicking: {type:Number}, 
    GKPositioning: {type:Number}, 
    GKReflexes: {type:Number}, 
    BestPosition: {type:String}, 
    BestOverallRating: {type:Number} 
});

module.exports = mongoose.model('dataSet', datSet);